service: food-look-api

frameworkVersion: ^2.72.0

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000

functions:
  graphql:
    handler: src/functions/graphql.handler
    role: ServiceRole
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get

resources:
